# test and build container
steps:
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: docker
    args:
      [
        "buildx",
        "build",
        "--build-arg",
        "CLUSTER_PROJECT=${_CLUSTER_PROJECT}",
        ".",
      ]

substitutions:
  _CLUSTER_PROJECT: sports-dev-experiments
