# release only, deploy with helm 3 + helm gcs plugin
steps:
  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - --tag=europe-docker.pkg.dev/sports-dev-experiments/eu/mcp/grafana:${_COMMIT_ID}
      - --tag=europe-docker.pkg.dev/sports-dev-experiments/eu/mcp/grafana:latest
      - .

  - id: "push-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - --all-tags
      - europe-docker.pkg.dev/sports-dev-experiments/eu/mcp/grafana

  - id: "deploy-eu"
    name: "europe-docker.pkg.dev/sports-dev-experiments/eu/sports-devops-build"
    entrypoint: sh
    secretEnv:
      - GRAFANA_SERVICE_ACCOUNT_TOKEN
    args:
      - "-c"
      - |
        helm template --name-template=${_APP_NAME} --namespace monitoring \
        --set image.tag=${_COMMIT_ID} \
        --set envVars.GRAFANA_SERVICE_ACCOUNT_TOKEN=$$GRAFANA_SERVICE_ACCOUNT_TOKEN \
        --values=./cd-assets/prod/values-envs.yaml \
        --values=./cd-assets/prod/values-httpserver.yaml \
        --repo=gs://${_GCS_BUCKET_NAME}/artifacts/kubershmuber-charts deployment-chart \
        | gke-deploy run -f - -a ${_APP_NAME} -n monitoring -o output-prod-eu -c ${_CLUSTER_NAME} --project ${_CLUSTER_PROJECT} -l ${_CLUSTER_REGION} --timeout=15m

substitutions:
  _APP_NAME: grafana-mcp
  _CLUSTER_NAME: kubershmuber-prod-eu
  _CLUSTER_PROJECT: kubershmuber-prod-sports
  _CLUSTER_REGION: europe-west1
  _COMMIT_ID: latest
  _GCS_BUCKET_NAME: kubershmuber-dev-private-sports-eu
  _REPO_NAME: grafana-mcp

availableSecrets:
  inline:
    - kmsKeyName: projects/kubershmuber-prod-credentials/locations/global/keyRings/global-keyring/cryptoKeys/cloud-build-key
      envMap:
        GRAFANA_SERVICE_ACCOUNT_TOKEN: "CiQAbRA+mcL8OEnz/ytiYO1zLRwZ/XXYhpIyMt910PdW/5UG/lASVwA64weC/rw7USpVf/2Af7NxYG7OcyuXmux29DIaW/YmO8e0fZfdLHL0KxeP3gz9kwsZHKXZ4vtUx0SENpc0uvfDnCfhD4BVU08OFnQp29oZIGNNG2EMzg==" # run `make encrypt-prod` to generate

logsBucket: "gs://kubershmuber-dev-prod-sports-devops-logs"
